In [61]:
import pandas as pd
import numpy as np
from datetime import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import pathlib

import sklearn


from copy import deepcopy
random_state: int = 42

pd.set_option('display.max_columns', None)

## import local lib

import api.utils

In [26]:
PROJECT_ROOT = pathlib.Path.cwd().parent
data_path = PROJECT_ROOT / 'data' / 'processed' / 'processed_data.csv'

In [28]:
_processed_df = pd.read_csv( data_path )
_processed_df.shape

(8849, 12)

In [29]:
processed_df = deepcopy( _processed_df )
processed_df = processed_df.drop( columns= ['start_time', 'end_time', 'modified_date'], errors= 'ignore'  )

processed_df.head(2)

,emissions_quantity,emissions_factor,capacity,capacity_factor,activity,source_type,state,area,pop2020
0,214000.0,0.513,138.0,0.345,417000.0,gas,Alabama,12.899239,5024279.0
1,204000.0,0.513,138.0,0.329,398000.0,gas,Alabama,12.899239,5024279.0

In [30]:
## setting proper dtypes
num_cols = [
    'emissions_quantity', 'capacity', 'capacity_factor', 'activity',
    'area', 'pop2020'
]

cat_cols = ['state', 'source_type']

for c in num_cols:
    if c in processed_df.columns:
        processed_df[c] = pd.to_numeric(processed_df[c], errors='coerce')

for c in cat_cols:
    if c in processed_df.columns:
        processed_df[c] = processed_df[c].astype('string').str.strip()

In [31]:
processed_df[ num_cols ].describe()
processed_df.head()

,emissions_quantity,emissions_factor,capacity,capacity_factor,activity,source_type,state,area,pop2020
0,214000.0,0.513,138.0,0.345,417000.0,gas,Alabama,12.899239,5024279.0
1,204000.0,0.513,138.0,0.329,398000.0,gas,Alabama,12.899239,5024279.0
2,209000.0,0.515,138.0,0.335,406000.0,gas,Alabama,12.899239,5024279.0
3,201000.0,0.513,138.0,0.324,392000.0,gas,Alabama,12.899239,5024279.0
4,113000.0,0.452,87.0,0.328,250000.0,gas,Texas,65.363350,29145505.0

In [38]:
'  asd  a aa'.replace( ' ', '' )
processed_df['state'].unique()
processed_df['source_type'].unique()

<StringArray>
['gas', 'oil', 'coal', 'other_fossil', 'biomass', 'waste']
Length: 6, dtype: string

In [74]:

feature_df = (  deepcopy( processed_df )
	# 1) transforms + ratios 
	.assign(
		log1p_activity=         lambda df:  np.log1p(  df['activity']  ),
		log1p_capacity=         lambda df:  np.log1p(  df['capacity']  ),
		log1p_pop2020=          lambda df:  np.log1p(  df['pop2020']  ),
		log1p_area=             lambda df:  np.log1p(  df['area']  ),
		log1Pop_density=      		lambda df:  np.log1p(  df['pop2020'] / df['area'].replace(  0, np.nan  )  ),
		activity_per_capita=    lambda df:  df['activity'] / df['pop2020'].replace(  0, np.nan  ),
		activity_per_area=      lambda df:  df['activity'] / df['area'].replace(  0, np.nan  ),
		capacity_per_capita=    lambda df:  df['capacity'] / df['pop2020'].replace(  0, np.nan  ),
		capacity_density=       lambda df:  df['capacity'] / df['area'].replace(  0, np.nan  ),

	# 2) power-system structure features 
		potential_output=               lambda df:  df['capacity'] * df['capacity_factor'],
		utilization_ratio=              lambda df:  df['activity'] / (  (df['capacity'] * df['capacity_factor']).replace(  0, np.nan  )  ),
		activity_capacityFactor=     lambda df:  df['activity'] * df['capacity_factor'],
		activity_per_capacity=          lambda df:  df['activity'] / df['capacity'].replace(  0, np.nan  ),
		activity_capacity=      lambda df:  df['activity'] * df['log1p_capacity'],
		capacity_factor_capacity=       lambda df: df['capacity_factor'] * df['log1p_capacity'],
	## 3. interaction features
		state =  lambda df: df['state'].str.replace( ' ', '' ),
		source_type =  lambda df: df['source_type'].str.replace( '_', '' ),
		inter =  lambda df: df.apply( lambda _df: f"{_df['state']}_{_df['source_type']}", axis= 'columns'   ) ,
	
	)
    ## One-hot encoding for state & interaction-field
    .pipe( api.utils.OHE_func, categorical_col= ['state', 'inter']  )
    
    
	.drop( columns= ['emissions_factor'] ) ## as using this field would leakage the data
)
feature_df.shape
feature_df.head()

(8849, 244)

In [66]:
feature_OHE_df = api.utils.OHE_func( feature_df, categorical_col= ['state', 'state_sourceType'] )

In [67]:
feature_OHE_df

,emissions_quantity,capacity,capacity_factor,activity,source_type,area,pop2020,log1p_activity,log1p_capacity,log1p_pop2020,log1p_area,log1Pop_density,activity_per_capita,activity_per_area,capacity_per_capita,capacity_density,potential_output,utilization_ratio,activity_capacityFactor,activity_per_capacity,activity_capacity,capacity_factor_capacity,state_Arizona,state_Arkansas,state_California,state_Colorado,state_Connecticut,state_Delaware,state_DistrictofColumbia,state_Florida,state_Georgia,state_Idaho,state_Illinois,state_Indiana,state_Iowa,state_Kansas,state_Kentucky,state_Louisiana,state_Maine,state_Maryland,state_Massachusetts,state_Michigan,state_Minnesota,state_Mississippi,state_Missouri,state_Montana,state_Nebraska,state_Nevada,state_NewHampshire,state_NewJersey,state_NewMexico,state_NewYork,state_NorthCarolina,state_NorthDakota,state_Ohio,state_Oklahoma,state_Oregon,state_Pennsylvania,state_RhodeIsland,state_SouthCarolina,state_SouthDakota,state_Tennessee,state_Texas,state_Utah,state_Vermont,state_Virginia,state_Washington,state_WestVirginia,state_Wisconsin,state_Wyoming,state_sourceType_Alabama_coal,state_sourceType_Alabama_gas,state_sourceType_Alabama_oil,state_sourceType_Arizona_coal,state_sourceType_Arizona_gas,state_sourceType_Arizona_oil,state_sourceType_Arkansas_biomass,state_sourceType_Arkansas_coal,state_sourceType_Arkansas_gas,state_sourceType_California_coal,state_sourceType_California_gas,state_sourceType_California_oil,state_sourceType_California_other_fossil,state_sourceType_California_waste,state_sourceType_Colorado_coal,state_sourceType_Colorado_gas,state_sourceType_Colorado_oil,state_sourceType_Connecticut_coal,state_sourceType_Connecticut_gas,state_sourceType_Connecticut_oil,state_sourceType_Connecticut_waste,state_sourceType_Delaware_coal,state_sourceType_Delaware_gas,state_sourceType_Delaware_oil,state_sourceType_DistrictofColumbia_gas,state_sourceType_Florida_coal,state_sourceType_Florida_gas,state_sourceType_Florida_oil,state_sourceType_Florida_other_fossil,state_sourceType_Florida_waste,state_sourceType_Georgia_biomass,state_sourceType_Georgia_coal,state_sourceType_Georgia_gas,state_sourceType_Georgia_oil,state_sourceType_Georgia_other_fossil,state_sourceType_Idaho_gas,state_sourceType_Idaho_other_fossil,state_sourceType_Illinois_coal,state_sourceType_Illinois_gas,state_sourceType_Illinois_oil,state_sourceType_Indiana_coal,state_sourceType_Indiana_gas,state_sourceType_Indiana_oil,state_sourceType_Indiana_other_fossil,state_sourceType_Iowa_coal,state_sourceType_Iowa_gas,state_sourceType_Iowa_oil,state_sourceType_Iowa_other_fossil,state_sourceType_Kansas_coal,state_sourceType_Kansas_gas,state_sourceType_Kansas_oil,state_sourceType_Kentucky_coal,state_sourceType_Kentucky_gas,state_sourceType_Kentucky_oil,state_sourceType_Louisiana_biomass,state_sourceType_Louisiana_coal,state_sourceType_Louisiana_gas,state_sourceType_Louisiana_other_fossil,state_sourceType_Louisiana_waste,state_sourceType_Maine_biomass,state_sourceType_Maine_gas,state_sourceType_Maine_oil,state_sourceType_Maine_waste,state_sourceType_Maryland_coal,state_sourceType_Maryland_gas,state_sourceType_Maryland_oil,state_sourceType_Maryland_waste,state_sourceType_Massachusetts_gas,state_sourceType_Massachusetts_oil,state_sourceType_Massachusetts_waste,state_sourceType_Michigan_coal,state_sourceType_Michigan_gas,state_sourceType_Michigan_oil,state_sourceType_Michigan_other_fossil,state_sourceType_Michigan_waste,state_sourceType_Minnesota_coal,state_sourceType_Minnesota_gas,state_sourceType_Minnesota_oil,state_sourceType_Minnesota_waste,state_sourceType_Mississippi_coal,state_sourceType_Mississippi_gas,state_sourceType_Mississippi_oil,state_sourceType_Missouri_coal,state_sourceType_Missouri_gas,state_sourceType_Missouri_oil,state_sourceType_Montana_coal,state_sourceType_Montana_gas,state_sourceType_Montana_other_fossil,state_sourceType_Nebraska_coal,state_sourceType_Nebraska_gas,state_sourceType_Nebraska_oil,state_sourceType_Nevada_coal,state_sourceType_Nevada_gas,state_sourceType_NewHampshire_coal,state_sourceType_NewHampshire_gas,state_sourceType_NewHampshire_oil,state_sourceType_NewHampshire_waste,state_sourceType_NewJersey_coal,state_sourceType_NewJersey_gas,state_sourceType_NewJersey_oil,state_sourceType_NewJersey_other_fossil,state_sourceType_NewJersey_waste,state_sourceType_NewMexico_coal,state_sourceType_NewMexico_gas,state_sourceType_NewMexico_oil,state_sourceType_NewMexico_other_fossil,state_sourceType_NewYork_coal,state_sourceType_NewYork_gas,state_sourceType_NewYork_oil,state_sourceType_NewYork_waste,state_sourceType_NorthCarolina_coal,state_sourceType_NorthCarolina_gas,state_sourceType_NorthCarolina_oil,state_sourceType_NorthCarolina_other_fossil,state_sourceType_NorthDakota_coal,state_sourceType_NorthDakota_gas,state_sourceType_Ohio_biomass,state_sourceType_Ohio_coal,state_sourceType_Ohio_gas,state_sourceType_Ohio_oil,state_sourceType_Ohio_other_fossil,state_sourceType_Oklahoma_coal,state_sourceType_Oklahoma_gas,state_sourceType_Oklahoma_oil,state_sourceType_Oklahoma_waste,state_sourceType_Oregon_coal,state_sourceType_Oregon_gas,state_sourceType_Oregon_waste,state_sourceType_Pennsylvania_biomass,state_sourceType_Pennsylvania_coal,state_sourceType_Pennsylvania_gas,state_sourceType_Pennsylvania_oil,state_sourceType_Pennsylvania_other_fossil,state_sourceType_Pennsylvania_waste,state_sourceType_RhodeIsland_gas,state_sourceType_SouthCarolina_coal,state_sourceType_SouthCarolina_gas,state_sourceType_SouthCarolina_oil,state_sourceType_SouthDakota_coal,state_sourceType_SouthDakota_gas,state_sourceType_SouthDakota_oil,state_sourceType_Tennessee_biomass,state_sourceType_Tennessee_coal,state_sourceType_Tennessee_gas,state_sourceType_Tennessee_oil,state_sourceType_Texas_coal,state_sourceType_Texas_gas,state_sourceType_Texas_oil,state_sourceType_Texas_other_fossil,state_sourceType_Texas_waste,state_sourceType_Utah_coal,state_sourceType_Utah_gas,state_sourceType_Utah_oil,state_sourceType_Utah_other_fossil,state_sourceType_Vermont_oil,state_sourceType_Virginia_biomass,state_sourceType_Virginia_coal,state_sourceType_Virginia_gas,state_sourceType_Virginia_oil,state_sourceType_Virginia_waste,state_sourceType_Washington_biomass,state_sourceType_Washington_coal,state_sourceType_Washington_gas,state_sourceType_Washington_waste,state_sourceType_WestVirginia_coal,state_sourceType_WestVirginia_gas,state_sourceType_WestVirginia_oil,state_sourceType_Wisconsin_biomass,state_sourceType_Wisconsin_coal,state_sourceType_Wisconsin_gas,state_sourceType_Wisconsin_oil,state_sourceType_Wisconsin_other_fossil,state_sourceType_Wyoming_coal,state_sourceType_Wyoming_gas
0,214000.0,138.0,0.345,417000.0,gas,12.899239,5024279.0,12.940844,4.934474,15.429793,2.631834,12.872627,0.082997,32327.489578,0.000027,10.698306,47.610,8758.664146,143865.0,3021.739130,2.057676e+06,1.702394,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,204000.0,138.0,0.329,398000.0,gas,12.899239,5024279.0,12.894210,4.934474,15.429793,2.631834,12.872627,0.079215,30854.534417,0.000027,10.698306,45.402,8766.133650,130942.0,2884.057971,1.963921e+06,1.623442,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,209000.0,138.0,0.335,406000.0,gas,12.899239,5024279.0,12.914111,4.934474,15.429793,2.631834,12.872627,0.080808,31474.726064,0.000027,10.698306,46.230,8782.176076,136010.0,2942.028986,2.003396e+06,1.653049,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,201000.0,138.0,0.324,392000.0,gas,12.899239,5024279.0,12.879020,4.934474,15.429793,2.631834,12.872627,0.078021,30389.390682,0.000027,10.698306,44.712,8767.221328,127008.0,2840.579710,1.934314e+06,1.598770,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,113000.0,87.0,0.328,250000.0,gas,65.363350,29145505.0,12.429220,4.477337,17.187811,4.195145,13.007852,0.008578,3824.773392,0.000003,1.331021,28.536,8760.863471,82000.0,2873.563218,1.119334e+06,1.468566,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8844,1230000.0,1267.0,0.345,3830000.0,gas,17.081225,10077331.0,15.158376,7.145196,16.125799,2.894874,13.287821,0.380061,224222.790343,0.000126,74.175007,437.115,8761.996271,1321350.0,3022.888713,2.736610e+07,2.465093,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8845,32000.0,35.0,0.323,99000.0,gas,17.081225,10077331.0,11.502885,3.583519,16.125799,2.894874,13.287821,0.009824,5795.837139,0.000003,2.049033,11.305,8757.187085,31977.0,2828.571429,3.547684e+05,1.157477,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8846,32000.0,35.0,0.329,101000.0,gas,17.081225,10077331.0,11.522886,3.583519,16.125799,2.894874,13.287821,0.010022,5912.924758,0.000003,2.049033,11.515,8771.168042,33229.0,2885.714286,3.619354e+05,1.178978,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8847,33000.0,35.0,0.335,103000.0,gas,17.081225,10077331.0,11.542494,3.583519,16.125799,2.894874,13.287821,0.010221,6030.012377,0.000003,2.049033,11.725,8784.648188,34505.0,2942.857143,3.691025e+05,1.200479,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8848,34000.0,35.0,0.346,106000.0,gas,17.081225,10077331.0,11.571204,3.583519,16.125799,2.894874,13.287821,0.010519,6205.643806,0.000003,2.049033,12.110,8753.096614,36676.0,3028.571429,3.798530e+05,1.239898,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
## import local lib
 api.utils

array(['state_Arizona', 'state_Arkansas', 'state_California',
       'state_Colorado', 'state_Connecticut', 'state_Delaware',
       'state_DistrictofColumbia', 'state_Florida', 'state_Georgia',
       'state_Idaho', 'state_Illinois', 'state_Indiana', 'state_Iowa',
       'state_Kansas', 'state_Kentucky', 'state_Louisiana', 'state_Maine',
       'state_Maryland', 'state_Massachusetts', 'state_Michigan',
       'state_Minnesota', 'state_Mississippi', 'state_Missouri',
       'state_Montana', 'state_Nebraska', 'state_Nevada',
       'state_NewHampshire', 'state_NewJersey', 'state_NewMexico',
       'state_NewYork', 'state_NorthCarolina', 'state_NorthDakota',
       'state_Ohio', 'state_Oklahoma', 'state_Oregon',
       'state_Pennsylvania', 'state_RhodeIsland', 'state_SouthCarolina',
       'state_SouthDakota', 'state_Tennessee', 'state_Texas',
       'state_Utah', 'state_Vermont', 'state_Virginia',
       'state_Washington', 'state_WestVirginia', 'state_Wisconsin',
       'state_Wyoming', 'state_sourceType_Alabama__coal',
       'state_sourceType_Alabama__gas', 'state_sourceType_Alabama__oil',
       'state_sourceType_Arizona__coal', 'state_sourceType_Arizona__gas',
       'state_sourceType_Arizona__oil',
       'state_sourceType_Arkansas__biomass',
       'state_sourceType_Arkansas__coal',
       'state_sourceType_Arkansas__gas',
       'state_sourceType_California__coal',
       'state_sourceType_California__gas',
       'state_sourceType_California__oil',
       'state_sourceType_California__other_fossil',
       'state_sourceType_California__waste',
       'state_sourceType_Colorado__coal',
       'state_sourceType_Colorado__gas', 'state_sourceType_Colorado__oil',
       'state_sourceType_Connecticut__coal',
       'state_sourceType_Connecticut__gas',
       'state_sourceType_Connecticut__oil',
       'state_sourceType_Connecticut__waste',
       'state_sourceType_Delaware__coal',
       'state_sourceType_Delaware__gas', 'state_sourceType_Delaware__oil',
       'state_sourceType_DistrictofColumbia__gas',
       'state_sourceType_Florida__coal', 'state_sourceType_Florida__gas',
       'state_sourceType_Florida__oil',
       'state_sourceType_Florida__other_fossil',
       'state_sourceType_Florida__waste',
       'state_sourceType_Georgia__biomass',
       'state_sourceType_Georgia__coal', 'state_sourceType_Georgia__gas',
       'state_sourceType_Georgia__oil',
       'state_sourceType_Georgia__other_fossil',
       'state_sourceType_Idaho__gas',
       'state_sourceType_Idaho__other_fossil',
       'state_sourceType_Illinois__coal',
       'state_sourceType_Illinois__gas', 'state_sourceType_Illinois__oil',
       'state_sourceType_Indiana__coal', 'state_sourceType_Indiana__gas',
       'state_sourceType_Indiana__oil',
       'state_sourceType_Indiana__other_fossil',
       'state_sourceType_Iowa__coal', 'state_sourceType_Iowa__gas',
       'state_sourceType_Iowa__oil',
       'state_sourceType_Iowa__other_fossil',
       'state_sourceType_Kansas__coal', 'state_sourceType_Kansas__gas',
       'state_sourceType_Kansas__oil', 'state_sourceType_Kentucky__coal',
       'state_sourceType_Kentucky__gas', 'state_sourceType_Kentucky__oil',
       'state_sourceType_Louisiana__biomass',
       'state_sourceType_Louisiana__coal',
       'state_sourceType_Louisiana__gas',
       'state_sourceType_Louisiana__other_fossil',
       'state_sourceType_Louisiana__waste',
       'state_sourceType_Maine__biomass', 'state_sourceType_Maine__gas',
       'state_sourceType_Maine__oil', 'state_sourceType_Maine__waste',
       'state_sourceType_Maryland__coal',
       'state_sourceType_Maryland__gas', 'state_sourceType_Maryland__oil',
       'state_sourceType_Maryland__waste',
       'state_sourceType_Massachusetts__gas',
       'state_sourceType_Massachusetts__oil',
       'state_sourceType_Massachusetts__waste',
       'state_sourceType_Michigan__coal',
       'state_sourceType_Michigan__gas', 'state_sourceType_Michigan__oil',
       'state_sourceType_Michigan__other_fossil',
       'state_sourceType_Michigan__waste',
       'state_sourceType_Minnesota__coal',
       'state_sourceType_Minnesota__gas',
       'state_sourceType_Minnesota__oil',
       'state_sourceType_Minnesota__waste',
       'state_sourceType_Mississippi__coal',
       'state_sourceType_Mississippi__gas',
       'state_sourceType_Mississippi__oil',
       'state_sourceType_Missouri__coal',
       'state_sourceType_Missouri__gas', 'state_sourceType_Missouri__oil',
       'state_sourceType_Montana__coal', 'state_sourceType_Montana__gas',
       'state_sourceType_Montana__other_fossil',
       'state_sourceType_Nebraska__coal',
       'state_sourceType_Nebraska__gas', 'state_sourceType_Nebraska__oil',
       'state_sourceType_Nevada__coal', 'state_sourceType_Nevada__gas',
       'state_sourceType_NewHampshire__coal',
       'state_sourceType_NewHampshire__gas',
       'state_sourceType_NewHampshire__oil',
       'state_sourceType_NewHampshire__waste',
       'state_sourceType_NewJersey__coal',
       'state_sourceType_NewJersey__gas',
       'state_sourceType_NewJersey__oil',
       'state_sourceType_NewJersey__other_fossil',
       'state_sourceType_NewJersey__waste',
       'state_sourceType_NewMexico__coal',
       'state_sourceType_NewMexico__gas',
       'state_sourceType_NewMexico__oil',
       'state_sourceType_NewMexico__other_fossil',
       'state_sourceType_NewYork__coal', 'state_sourceType_NewYork__gas',
       'state_sourceType_NewYork__oil', 'state_sourceType_NewYork__waste',
       'state_sourceType_NorthCarolina__coal',
       'state_sourceType_NorthCarolina__gas',
       'state_sourceType_NorthCarolina__oil',
       'state_sourceType_NorthCarolina__other_fossil',
       'state_sourceType_NorthDakota__coal',
       'state_sourceType_NorthDakota__gas',
       'state_sourceType_Ohio__biomass', 'state_sourceType_Ohio__coal',
       'state_sourceType_Ohio__gas', 'state_sourceType_Ohio__oil',
       'state_sourceType_Ohio__other_fossil',
       'state_sourceType_Oklahoma__coal',
       'state_sourceType_Oklahoma__gas', 'state_sourceType_Oklahoma__oil',
       'state_sourceType_Oklahoma__waste',
       'state_sourceType_Oregon__coal', 'state_sourceType_Oregon__gas',
       'state_sourceType_Oregon__waste',
       'state_sourceType_Pennsylvania__biomass',
       'state_sourceType_Pennsylvania__coal',
       'state_sourceType_Pennsylvania__gas',
       'state_sourceType_Pennsylvania__oil',
       'state_sourceType_Pennsylvania__other_fossil',
       'state_sourceType_Pennsylvania__waste',
       'state_sourceType_RhodeIsland__gas',
       'state_sourceType_SouthCarolina__coal',
       'state_sourceType_SouthCarolina__gas',
       'state_sourceType_SouthCarolina__oil',
       'state_sourceType_SouthDakota__coal',
       'state_sourceType_SouthDakota__gas',
       'state_sourceType_SouthDakota__oil',
       'state_sourceType_Tennessee__biomass',
       'state_sourceType_Tennessee__coal',
       'state_sourceType_Tennessee__gas',
       'state_sourceType_Tennessee__oil', 'state_sourceType_Texas__coal',
       'state_sourceType_Texas__gas', 'state_sourceType_Texas__oil',
       'state_sourceType_Texas__other_fossil',
       'state_sourceType_Texas__waste', 'state_sourceType_Utah__coal',
       'state_sourceType_Utah__gas', 'state_sourceType_Utah__oil',
       'state_sourceType_Utah__other_fossil',
       'state_sourceType_Vermont__oil',
       'state_sourceType_Virginia__biomass',
       'state_sourceType_Virginia__coal',
       'state_sourceType_Virginia__gas', 'state_sourceType_Virginia__oil',
       'state_sourceType_Virginia__waste',
       'state_sourceType_Washington__biomass',
       'state_sourceType_Washington__coal',
       'state_sourceType_Washington__gas',
       'state_sourceType_Washington__waste',
       'state_sourceType_WestVirginia__coal',
       'state_sourceType_WestVirginia__gas',
       'state_sourceType_WestVirginia__oil',
       'state_sourceType_Wisconsin__biomass',
       'state_sourceType_Wisconsin__coal',
       'state_sourceType_Wisconsin__gas',
       'state_sourceType_Wisconsin__oil',
       'state_sourceType_Wisconsin__other_fossil',
       'state_sourceType_Wyoming__coal', 'state_sourceType_Wyoming__gas'],
      dtype=object)

In [ ]:
# example usage
# df = pd.read_excel('processed_data.xlsx')
# feat_df = make_features_no_time(df, keep_year=False, add_oof_priors=True)
# feat_df.head()